config/routes.rb
Rails.application.routes.draw do
  
  get '/dashboard', as: :dashboard, to: 'dashboard#show'
  get '/auth/google_oauth2', as: :login
  get '/auth/google_oauth2/callback', to: 'sessions#create', as: :callback
  get '/logout', as: :logout, to: 'sessions#destroy'
  resources :trips, only: [:new]
  
  root 'welcome#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :uid,
    presence: true
  validates :email,
    presence: true,
    uniqueness: true
  validates :first_name,
    presence: true
  validates :last_name,
    presence: true
  validates :image,
    presence: true
  
  def self.find_or_create_from_oauth(oauth)
    user = User.find_or_create_by(uid: oauth.uid)

    user.uid           = oauth.uid
    user.email         = oauth.info.email
    user.first_name    = oauth.info.first_name
    user.last_name     = oauth.info.last_name
    user.image         = oauth.info.image
    user.save
    
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  before_filter :expire_hsts
  
  helper_method :current_user
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  private
  
  def expire_hsts
    response.headers["Strict-Transport-Security"] = 'max-age=0'
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
if Rails.env != "development"
  force_ssl only: [:create]
end
  
  def create
    @user = User.find_or_create_from_oauth(oauth)
    if @user
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      redirect_to root_path
    end
  end
  
  def destroy
    session.destroy
    redirect_to root_path
  end

  private
  
  def oauth
    request.env["omniauth.auth"]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/show.html.erb
<!DOCTYPE html>
<html>

<body id="dashboard">
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="index-guide form-title">Welcome, <%= current_user.first_name %>!<br> Let's find something off the beaten path...</h1>
    </div>
  </div>
</div>

<div class="container">
  <!-- Example row of columns -->
  <form>
    <div class="row index-guides">
      <div class="col-md-6">
        <h2 class="index-guide form-title">Origin:</h2>
        <div class="form-group">
          <input type="text" class="form-control" id="origin-field" placeholder="Address or City">
        </div>
      </div>
      <div class="col-md-6">
        <h2 class="index-guide form-title">Destination:</h2>
        <div class="form-group">
          <input type="text" class="form-control" id="destination-field" placeholder="Address or City">
        </div>
      </div>
      <button type="submit" class="btn btn-primary btn-lg" id="route-submit">Submit</button>
    </div>
  </form>
</div> <!-- /container -->

<div class="container">
  <div class="row">
    <div class="col-md-12" id="place-title-container">
      <h2 class="index-guide" id="place-title"></h2><br>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-3" id="next-button">
    </div>
    <div class="col-md-3" id="directions-button">
    </div>
    <div class="col-md-3"></div>
  </div>
</div>

<div id="map-container">
  <div id="map-canvas"></div>
</div>

<div class="container">
  <div class="row" id="directions-row">
    <div class="col-md-12" id="directions-col">
      <div id="directions-panel"></div>
    </div>
  </div>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoadTripper</title>
  <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <script type="text/javascript"
          src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLE_API_KEY"] %>&libraries=places,geometry">
  </script>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <p class="roadtripper-logo-text">RoadTripper</p>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <p class="roadtripper-logo-text"><%= current_user.first_name %></p>
          </li>
          <li>
            <img src="<%= current_user.image %>" alt="user-image" class="img-circle img-responsive center-block">
          </li>
          <li>
            <a href="<%= logout_path %>" id="roadtripper-logout">Logout</a>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
    </nav>
  <% end %>

<%= yield %>

</body>
</html>

app/views/trips/new.html.erb
<%= @trip.steps %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>Bootstrap 101 Template</title>

  <!-- Bootstrap -->
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body>

<div class="jumbotron" id="welcome-jumbo">
  <div class="container">
    <div class="welcome-container">
      <h1 class="welcome-text">RoadTripper</h1>
      <p class="welcome-text">Helping you discover the best your road trip has to offer</p>
      <p class="welcome-button"><a class="btn btn-default btn-lg" href="<%= login_path %>" role="button">Hit the Road!</a></p>
    </div>
    <div class="row">
      <div class="col-md-12">
        <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <!-- Example row of columns -->
  <div class="row index-guides">
    <div class="col-md-4">
      <h2 class="index-guide">Why</h2>
      <p class="index-text">Because road trips are fun! Planning road trips isn't always as easy, though. We're travel enthusiasts ourselves and we know how much effort goes into planning the perfect trip. Connecting road trippers with the best routes to make the most of their trips is why we do what we do. </p>
    </div>
    <div class="col-md-4">
      <h2 class="index-guide">What</h2>
      <p class="index-text">We help you plan the perfect road trip. We all know the big cities have tons to offer, and easy pickings on road trips, but what about stops you never would have thought of? We can give you a cool new suggestion based on where you are and where you're going, and we'll even map out the fastest route so you can make the most of your time. </p>
    </div>
    <div class="col-md-4">
      <h2 class="index-guide">How</h2>
      <p class="index-text">We've done our research, and we use our findings to help you find something interesting to explore based on where you're going. We're big fans of wandering off the beaten path and discovering hidden gems, so login, tell us about your trip, and will give you something new and fresh to check out. </p>
    </div>
  </div>
</div> <!-- /container -->

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2 class="index-guide">Planning a trip of your own?</h2>
      <p class="welcome-button"><a class="btn btn-primary btn-lg" href="<%= login_path %>" role="button">Get Started!</a></p>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <hr>

      <footer>
        <p>&copy; RoadTripper 2015</p>
      </footer>
    </div>
  </div>
</div>


<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.min.js"></script>
</body>
</html>